version: '3'
 
services:
  db:
    image: mysql
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: $MYSQL_NAME
      MYSQL_ROOT_USER: $MYSQL_USER
      MYSQL_ROOT_PASSWORD: $MYSQL_PASSWORD
    ports:
      - 3306:3306
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
    driver: local
